# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'JLKitDemo' do
#    pod 'JLContainer', :'0.0.2'
    pod 'JLContainer', :path => '~/Desktop/Github/Container-BaseViewController'
end
