# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'JLKitDemo' do
    pod 'SDWebImage', '~> 4.4.2'
    pod 'AFNetworking', '~> 3.2.1'
    pod 'JLContainer', :'0.0.6'
#    pod 'JLContainer', :path => '~/Desktop/Github/Container-BaseViewController'
end
